python3  stage2_batchtest_inpaint_model.py \
  --img_width 384 \
  --img_height 512 \
 --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" \
 --image_encoder_g_path="laion/CLIP-ViT-H-14-laion2B-s32B-b79K" \
 --image_encoder_p_path='facebook/dinov2-giant' \
 --batch_size=1 \
 --img_path='/root/autodl-tmp/data/test' \
 --save_path="./logs/view_stage2/384_512_long_mask" \
 --step_number=80000 \
 --calculate_metrics
