compute_environment: LOCAL_MACHINE
deepspeed_config:
 gradient_accumulation_steps: 1
 gradient_clipping: 1.0
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: false  # 不需要zero3初始化标志
 zero_stage: 2
distributed_type: DEEPSPEED
main_training_function: main
mixed_precision: bf16  # 改为bf16
num_machines: 1  # 改为2
num_processes: 2  # 改为4
use_cpu: false